--TASK 1
SELECT DISTINCT COMPANY from MANUFACTURER

--TASK 2
SELECT COUNT(*) FROM MANUFACTURER --COUNT(*) ALSO COUNTS NULL

--TASK 3
SELECT DISTINCT WARE FROM CATEGORY WHERE CLASS = 'Food'

--TASK 4
SELECT DISTINCT COMPANY FROM MANUFACTURER 
WHERE COMPANY LIKE 'A%' OR COMPANY LIKE 'B%' ORDER BY COMPANY ASC

--TASK 5
SELECT WARE FROM PRODUCT
EXCEPT SELECT WARE FROM MATERIAL

--TASK 6
SELECT WARE FROM MATERIAL
EXCEPT SELECT WARE FROM PRODUCT

--TASK 7
SELECT DISTINCT WARE FROM MATERIAL
INTERSECT SELECT DISTINCT WARE FROM PRODUCT

--TASK 8
SELECT DISTINCT MIN(PRICE), MAX(PRICE) FROM PRODUCT
WHERE WARE = 'Paper'

--TASK 9
SELECT ROUND(AVG(PRICE), 1), ROUND((AVG(PRICE * PRICE)-AVG(PRICE)*AVG(PRICE)), 1) FROM PRODUCT
WHERE WARE = 'Meat'