-- TASK 1
SELECT DISTINCT MANUFACTURER.COMPANY
FROM MANUFACTURER
INNER JOIN PRODUCT
ON PRODUCT.WARE='Drinking water'
WHERE MANUFACTURER.BILL_ID=PRODUCT.BILL_ID
ORDER BY MANUFACTURER.COMPANY ASC


--TASK 2
SELECT DISTINCT PRODUCT.WARE, MANUFACTURER.COMPANY
FROM MANUFACTURER, PRODUCT
INNER JOIN CATEGORY
ON CATEGORY.CLASS='Raw food'
WHERE CATEGORY.WARE=PRODUCT.WARE
ORDER BY PRODUCT.WARE, MANUFACTURER.COMPANY ASC


--TASK 3
SELECT DISTINCT PRODUCT.WARE
FROM  PRODUCT, MATERIAL
INNER JOIN CATEGORY
ON CATEGORY.CLASS='Mineral' AND CATEGORY.WARE=MATERIAL.WARE
WHERE MATERIAL.BILL_ID=PRODUCT.BILL_ID
ORDER BY PRODUCT.WARE ASC


--TASK 4
SELECT DISTINCT MANUFACTURER.COMPANY
FROM MANUFACTURER 
INNER JOIN CATEGORY, PRODUCT
ON CATEGORY.CLASS='Food' AND CATEGORY.WARE=PRODUCT.WARE
WHERE PRODUCT.BILL_ID=MANUFACTURER.BILL_ID

INTERSECT

SELECT DISTINCT MANUFACTURER.COMPANY
FROM MANUFACTURER 
INNER JOIN CATEGORY, PRODUCT
ON CATEGORY.CLASS='Fuel' AND CATEGORY.WARE=PRODUCT.WARE
WHERE PRODUCT.BILL_ID=MANUFACTURER.BILL_ID
ORDER BY MANUFACTURER.COMPANY ASC

--TASK 5
SELECT DISTINCT M1.COMPANY, P1.WARE || ' | ' || P2.WARE as PRODUCTS
FROM MANUFACTURER M1, PRODUCT P1, CATEGORY C1
INNER JOIN MANUFACTURER M2, PRODUCT P2, CATEGORY C2
ON M1.COMPANY = M2.COMPANY
WHERE C1.WARE = P1.WARE AND C1.CLASS = 'Food' AND C2.WARE = P2.WARE AND C2.CLASS = 'Fuel' AND M1.BILL_ID = P1.BILL_ID AND M2.BILL_ID = P2.BILL_ID
ORDER BY M1.COMPANY ASC

--TASK 6
SELECT DISTINCT M1.COMPANY --,P1.WARE || ' | ' || P2.WARE AS PRODUCTS
FROM MANUFACTURER M1, PRODUCT P1, CATEGORY C1
INNER JOIN MANUFACTURER M2, PRODUCT P2, CATEGORY C2
ON M1.COMPANY = M2.COMPANY
WHERE C1.CLASS = C2.CLASS AND C1.WARE = P1.WARE AND C2.WARE = P2.WARE AND M1.BILL_ID = P1.BILL_ID AND M2.BILL_ID = P2.BILL_ID AND P1.WARE <> P2.WARE
ORDER BY M1.COMPANY ASC

--TASK 7
SELECT P.WARE
FROM MATERIAL M, PRODUCT P
INNER JOIN CATEGORY C
ON C.CLASS = 'Mineral'
WHERE C.WARE = M.WARE AND P.BILL_ID = M.BILL_ID

EXCEPT

SELECT P.WARE
FROM MATERIAL M, PRODUCT P
INNER JOIN CATEGORY C
ON C.CLASS <> 'Mineral'
WHERE C.WARE = M.WARE AND P.BILL_ID = M.BILL_ID
ORDER BY P.WARE