--0
SELECT P.WARE AS PRODUCT, GROUP_CONCAT(DISTINCT m.WARE) AS MATERIALS
FROM PRODUCT P
JOIN MATERIAL M ON P.BILL_ID = M.BILL_ID
JOIN CATEGORY C ON C.WARE=P.WARE
WHERE C.CLASS='Food'
GROUP BY P.WARE;


--1
SELECT P.WARE AS PRODUCT, MIN(P.PRICE) AS MIN_PRICE, MAX(P.PRICE) AS MAX_PRICE
FROM PRODUCT P
GROUP BY P.WARE
ORDER BY P.WARE ASC;


--2
SELECT P.WARE AS PRODUCT, MIN(P.PRICE) AS MIN_PRICE, MAX(P.PRICE) AS MAX_PRICE, MAX(P.PRICE) - MIN(P.PRICE) AS DIFFERENCE
FROM PRODUCT P
GROUP BY P.WARE
ORDER BY DIFFERENCE DESC
LIMIT 3;


--3
SELECT M.COMPANY, GROUP_CONCAT(DISTINCT P.WARE) AS PRODUCTS 
FROM MANUFACTURER M
JOIN PRODUCT P ON P.BILL_ID=M.BILL_ID
GROUP BY M.COMPANY
ORDER BY COUNT(DISTINCT P.WARE) DESC
LIMIT 3;


--4
SELECT C.CLASS AS CATEGORY, /*P.WARE AS PRODUCT,*/ MAX(P.PRICE) AS MAX_PRICE
FROM CATEGORY C
JOIN PRODUCT P ON C.WARE = P.WARE
GROUP BY C.CLASS
ORDER BY C.CLASS ASC;


--5
SELECT MAN.COMPANY, GROUP_CONCAT(DISTINCT P.WARE) AS PRODUCT, GROUP_CONCAT(DISTINCT M.WARE) AS MATERIALS, M.BILL_ID
FROM MATERIAL M
JOIN MANUFACTURER MAN ON M.BILL_ID = MAN.BILL_ID
JOIN PRODUCT P ON M.BILL_ID = P.BILL_ID
GROUP BY MAN.COMPANY, M.BILL_ID
ORDER BY MAN.COMPANY ASC;


--6
SELECT MAN.COMPANY, GROUP_CONCAT(DISTINCT P.WARE) AS PRODUCT, GROUP_CONCAT(DISTINCT M.WARE) AS MATERIALS
FROM MANUFACTURER MAN
JOIN PRODUCT P ON MAN.BILL_ID = P.BILL_ID
LEFT JOIN MATERIAL M ON M.BILL_ID = MAN.BILL_ID
GROUP BY MAN.COMPANY
HAVING COUNT(DISTINCT P.WARE) > COUNT(DISTINCT M.WARE)
ORDER BY MAN.COMPANY ASC;


--7
SELECT MAN.COMPANY, GROUP_CONCAT(P.WARE) AS PRODUCT
FROM PRODUCT P
JOIN MANUFACTURER MAN ON P.BILL_ID = MAN.BILL_ID
GROUP BY MAN.COMPANY, P.WARE
HAVING COUNT(DISTINCT P.BILL_ID) > 2
ORDER BY MAN.COMPANY ASC;


--8 --USE IN
SELECT MAN.COMPANY,GROUP_CONCAT(DISTINCT C.CLASS) AS CLASS, GROUP_CONCAT(DISTINCT P.WARE) AS PRODUCT
FROM CATEGORY C
JOIN PRODUCT P ON C.WARE = P.WARE
JOIN MANUFACTURER MAN ON P.BILL_ID = MAN.BILL_ID
WHERE C.CLASS IN ('Mineral','Food','Fuel')
GROUP BY MAN.COMPANY
HAVING COUNT(DISTINCT C.CLASS) = 3
ORDER BY MAN.COMPANY ASC;


--9
SELECT MAN.COMPANY, /*GROUP_CONCAT(DISTINCT P.WARE) AS PRODUCT,*/ GROUP_CONCAT(DISTINCT CP.CLASS) AS PRODUCT_CALSS, /*GROUP_CONCAT(DISTINCT M.WARE) AS MATERIALS, */ GROUP_CONCAT(DISTINCT CM.CLASS) AS MATERIAL_CLASS
FROM MANUFACTURER MAN
JOIN PRODUCT P ON MAN.BILL_ID = P.BILL_ID
LEFT JOIN MATERIAL M ON P.BILL_ID = M.BILL_ID
LEFT JOIN CATEGORY CM ON M.WARE = CM.WARE
JOIN CATEGORY CP ON P.WARE = CP.WARE
GROUP BY MAN.COMPANY
ORDER BY MAN.COMPANY ASC;